### ISSUE TITLE
[FRONT] infowindow 의 design 논의

### ISSUE THREAD

**Issue by WHO-A-U** [KIMJINOH97/Hotplace-map#101]
# infowindow 의 design 논의
### 1. infowindow 에 들어가는 값
ex| 모든 값이 다 정보로 출력이 되야 하는지?

어떤 layout 을 채택 할건지

### 2. antdesign 에서 쓸만한 component

- Card	
-    Description
-    Statistic
-    Button
-    Tag
-

**Comment by KIMJINOH97** [comment]
### 추가

- 전체 글자 폰트 설정하기

**Comment by WHO-A-U** [comment]
![image](https://user-images.githubusercontent.com/59171080/136977349-1a1a3599-ddfc-4f78-a1c5-b940fe432625.png)
