### ISSUE TITLE
[CRAWLER] kakao.api 로 받아온 모든 record 들 kakao rating 초기화해주기

### ISSUE THREAD

**Issue by WHO-A-U** [KIMJINOH97/Hotplace-map#20]
request , urllib , bs4  이용해서 rating point 크롤링

**Comment by KIMJINOH97** [comment]
구현 완료 돌리면 됨.

**Comment by WHO-A-U** [comment]
![image](https://user-images.githubusercontent.com/59171080/118276986-3db91080-b503-11eb-9b40-83b0dfb2e947.png)
아직 update 되지 않은 record 들이15000개 남음


원래 4만개 데이터 존재했엇음
![image](https://user-images.githubusercontent.com/59171080/118277061-56292b00-b503-11eb-82a3-82b8ca977b68.png)
