### ISSUE TITLE
[DATA] 중복된 데이터 발견

### ISSUE THREAD

**Issue by WHO-A-U** [KIMJINOH97/Hotplace-map#23]
python 을 이용하여 중복데이터를 조회해보면 위와같이 중복된데이터가 적지 않게 나온다.

나중에 DELETE 할것
**DELETE 하기전에 반드시 백업을해야됨**
![image](https://user-images.githubusercontent.com/59171080/116512863-a7ca9680-a903-11eb-80b8-bd0ef57bd20a.png)

**Comment by KIMJINOH97** [comment]
<img width="498" alt="스크린샷 2021-04-30 오후 12 39 36" src="https://user-images.githubusercontent.com/62155304/116645607-229dbb00-a9b1-11eb-9794-a69d6fb9402b.png">
흠 주소도 똑같은데 뭘까

**Comment by KIMJINOH97** [comment]
![image](https://user-images.githubusercontent.com/62155304/116645728-5b3d9480-a9b1-11eb-9586-37f2d6593b1a.png)
카카오에도 여러개 뜨는거보니 얘네들이 여러개 지도에 넣은듯...
아마 이런 경우는 수작업? 으로 해야하나
행정동 문제도 있을듯
 '마포구 아현동' ,  '서대문구 북아현동'  이 두 곳이 겹치는 정보가 있는 듯

**Comment by KIMJINOH97** [comment]
기존 알고리즘 수정 1번 그림 -> 2번그림

**1 번**
![image](https://user-images.githubusercontent.com/62155304/116646349-c340aa80-a9b2-11eb-81f1-8c1df2f483d5.png)


**2번**

![image](https://user-images.githubusercontent.com/62155304/116646376-d6537a80-a9b2-11eb-9231-1a62fb324234.png)


이렇게 되면 북아현동 쪽에만 넣어짐.
