### ISSUE TITLE
[CRAWLER] 카카오와 네이버 사이 이슈 (해당 이슈 끝나면 체크)

### ISSUE THREAD

**Issue by KIMJINOH97** [KIMJINOH97/Hotplace-map#27]
- [x] **아래 해당하는 음식점이 디비에 담겨 있지 않음. (몇 개 확인)**
**ex) 연우김밥**
![image](https://user-images.githubusercontent.com/62155304/116804221-17d15a80-ab58-11eb-9315-d1403374113a.png)

- [x] **아래 해당하는 음식점의 별점이 없음.**
![image](https://user-images.githubusercontent.com/62155304/116804242-44857200-ab58-11eb-9465-0dc2e2353687.png)
**ex) 후계동**

- [x] **road_address 컬럼은 비울 것인지?? 아니면 까먹고 안 채웠나 ㅋ.ㅋㅋ (새로 채우면 되긴 함)**

**Comment by WHO-A-U** [comment]
아래 해당하는 음식점이 디비에 담겨 있지 않음아래 해당하는 음식점의 별점이 없음.
road_address 컬럼은 비울 것인지??
