### ISSUE TITLE
[CRAWLER] 네이버 크롤링 모듈 음식점 리스트 담기

### ISSUE THREAD

**Issue by KIMJINOH97** [KIMJINOH97/Hotplace-map#3]
해당하는 음식점 정보는 담아놨음. 문자열 처리해서 가게 이름, 별점 담으면 될듯.
아니면 직접 파싱해서 담아놓는 것도 가능

**Comment by WHO-A-U** [comment]
- 네이버 플레이스는 무조건 네이버 맵을 통해서 검색을 해야한다
- 중첩적인 iframe 동적태그 때문에 어쩔수 없이 selenium 을 사용해야만함
- iframe 을 bs(beautifulsoup)을 통해서 가져올때 load된후 가져와야할것

1. 왼쪽의 검색어를 사용하기 위해서 html 문서상 5번째 iframe (iframe[4]) 을 찾아서 
driver 메소드를 이용해서 검색을 해준다.
2. 그다음 가게들이 나와있는 리스트중 하나를 클릭
3. 클릭하면 새로운 iframe 이 할당이 되어 iframe 개수가 늘어난다
4. 오른쪽 정보에 driver가 접근하기 위해서는 
    1. 현재 위치한 (왼쪽 태두리 프레임) 에서 벗어난다
    2. 프레임을 다시 findall 한다
    3. 프레임이 하나 더 늘어난것을 확인할수 있다 (마지막 프레임 iframe[5]을 찾으면됨)
    4. 해당 프레임으로 들어가면 드디어 그림의 오른쪽 테두리 박스로 driver를 옮길수 있다.
5. 그 다음 bs를 통하여 다시 파싱

**Comment by WHO-A-U** [comment]
**🛠구현해야할 추가기능 네이버 크롤링 하단페이지 넘기기기능**

**Comment by WHO-A-U** [comment]
🛠네이버 크롤링 지번이 아닌 동이름을 가져오도록 수정
