### ISSUE TITLE
[DOCS] 필터링 쿼리 JSON format

### ISSUE THREAD

**Issue by WHO-A-U** [KIMJINOH97/Hotplace-map#61]
**다음과 같은 구조로 front -> back request 를 보내게 됨**

```javascript
{
  gu : [Integer] ,
  dong : [Integer] ,
  sub_category : [Integer] ,
  place_name: [String] ,
  minimum_kakao_rating: [Float] ,
  minimum_naver_rating: [Float] ,
  minimum_instagram_hashtag: [Integer] 
}
```

**Comment by KIMJINOH97** [comment]
- 생각해보니깐 이거 querydsl로하면 boolean 값들 다 없어도 될 것 같은데 어떻게 생각하나요.

**Comment by WHO-A-U** [comment]
minimum_naver_rating 을 null 로 처리하여 필터조건을 제외하는 방식은
사용자가 slider 의 값이 몇인지 변수로 계속 가지고 있어야 함

off 상태에서 on 상태로 toggle 할경우 null 값을 다시 기존저장해놓은 값 (<Slider> 값) 으로 
초기화해줘야 되는 번거로움이 있어 저렇게 처리한거였는데 

Front 에서 번거로움이 있긴하지만  API logic 을 구현할때 이득이라면 그렇게 바꿔볼 필요도 있을듯

**Comment by WHO-A-U** [comment]
![image](https://user-images.githubusercontent.com/59171080/130649612-ad69f1b8-ac18-43b7-a9f4-ad6b26dfc42f.png)

다음과 같이 requestdto 를 수정합니다

minimum_x_y  의 값들은 필터링을 적용할시 float 타입이 전송되고
필터링을 적용하지 않을시 null 값을 전송합니다

gu : [Integer]
dong : [Integer]
sub_category : [Integer]
place_name: [String]
minimum_kakao_rating: [Float] or [null]
minimum_naver_rating: [Float] or [null]
minimum_instagram_hashtag: [Integer] or [null]
