### ISSUE TITLE
[BACK, FRONT] SideBar 음식 리스트 및 장바구니 만들기

### ISSUE THREAD

**Issue by KIMJINOH97** [KIMJINOH97/Hotplace-map#71]
**음식 리스트**

왼쪽 사이드 바에 음식점의 정보들을 쉽게 볼 수 있게 하고자 함.

리스트 내용

foodListState
```
    {
      name: '상수동 밥한끼',
      naverRating: 4.5,
      kakaoRating: 4.5,
      instagramHashtag: 10000,
    }
```

초기 내용은 이정도로만 넣으면 될듯

한 페이지당 (4~5개) 정도

백앤드
- 페이징으로 querydsl 구현하기. (추후 정렬 생각해서 개선 예정)

프론트
- 사이드 바 음식점 페이징으로 구현 및 정보 넣기
- 사이드 바 음식점 지도에 마커 크기 다르게 나타내기

**Comment by WHO-A-U** [comment]
@KIMJINOH97 
## 리스트페이지화
```
카카오맵처럼 마커들은 지도에 한번에 작은 dot으로 보여주고
리스트에 해당되는 가게들만 마커로 보여주는 방식으로 개선
```

**Comment by WHO-A-U** [comment]
## #81 에서 구현완료
