### ISSUE TITLE
[FRONT] 특정 구,동에 지도가 안나오는 현상

### ISSUE THREAD

**Issue by KIMJINOH97** [KIMJINOH97/Hotplace-map#76]
![image](https://user-images.githubusercontent.com/62155304/131688039-059cf0e5-3265-4f83-9b47-617410096721.png)

### 에러 현상
- 특정 구의 동을 검색했을 때 다음과 같이 지도가 안나옴

**Comment by WHO-A-U** [comment]
원인 : DB 의 좌표값이 null 인 record 에 의해 생겨나는 현상

해결방안 
1. DB에서 해당 record 삭제
2. querydsl 로 filtering

**DB에서 해당 record 삭제함으로 이슈를 닫습니다**
