### ISSUE TITLE
[BACK] 회원기능 추가(SNS 로그인) 및 테이블

### ISSUE THREAD

**Issue by WHO-A-U** [KIMJINOH97/Hotplace-map#78]
# 회원기능

## 새로운 기능
1. 북마크 기능
2. 북마크된 장소 지도에 보여주기

## 추가되는 테이블

**MEMBER TABLE** (회원 테이블)

|  | attribute | type |
|--|---------- |-------|
|  |  id       |Integer |
|  |  name |String|
|  |  email |String|
|  |  profileUrl |String|
|  |  provider |String|
|  |  providerId|String|
|  |  createAt  |LocalDateTime|

**FAVORITE TABLE (즐겨찾기 테이블 )**

|  | attribute | type |
|--|---------- |-------|
|  |  id       |Integer |
|  |  userId |Integer|
|  |  storeId | Integer|
|  |  createAt  |LocalDateTime|

## ERD
![image](https://user-images.githubusercontent.com/59171080/134777941-fdfe3db4-1d6e-4dea-a282-9d848c73447c.png)

## 필요한 의존성 모듈
![image](https://user-images.githubusercontent.com/59171080/134775636-74078948-88cc-479c-8ed6-c9690e197e4c.png)
```gradle
dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
  implementation 'org.springframework.boot:spring-boot-starter-security'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.springframework.security:spring-security-test'
}
```

### jjwt
```gradle
dependencies {
    implementation 'io.jsonwebtoken:jjwt-api:0.11.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2',
            // Uncomment the next line if you want to use RSASSA-PSS (PS256, PS384, PS512) algorithms:
            //'org.bouncycastle:bcprov-jdk15on:1.60',
            'io.jsonwebtoken:jjwt-jackson:0.11.2' // or 'io.jsonwebtoken:jjwt-gson:0.11.2' for gson
}
```

**Comment by KIMJINOH97** [comment]
**member에 profile_url이 없어 DB와 코드에 추가했습니다.**

**Comment by KIMJINOH97** [comment]
- 로그인 시 받아오는 정보
```
{
    "userId":1,
    "providerId":"1935091815",
    "email":"rlawlsdh1127@naver.com",
    "profileUrl": "사용자 profile_url"
    "token":"jwt_token"
}
```

**Comment by WHO-A-U** [comment]
## https://github.com/KIMJINOH97/Hotplace-map/pull/88#discussion_r721116932

설계 방향 변경

* 로그인 성공시 토큰만 받고
* 토큰을 이용하여 사용자의 정보를 받아오는 API 는 따로 설계
