### ISSUE TITLE
[DOCS] user 관련 API 명세 및 세부 DTO 논의

### ISSUE THREAD

**Issue by WHO-A-U** [KIMJINOH97/Hotplace-map#94]
# user 관련 API 설계

## 필요한 API
* 사용자 정보 받아오기
* 북마크 하기
* 내가 한 북마크 가져오기

## API 명세
localhost:8080/user/?
| 기능 | METHOD |url | request | response|
| --- | ---|---- | ------- | ------| 
| 사용자 정보 받아오기 | GET|localhost:8080/user/info | token | UserInfoResponse.java | 
| 북마크 하기 | POST|localhost:8080/user/bookmark/{id} | token , {id} | PlaceResponse.java  |
| 내가 한 북마크 가져오기 | GET|localhost:8080/user/bookmark | token | PlaceResponse.java |

> {id} 는 place_id 를 말함

> 논의해야될 사항

## DTO 
**필수값만 일단 적음**
* 사용자 정보 받아오기
    * request  
        token 
    * response  
         이름 , 이메일 ,profile_url 

* 북마크 하기
    * request  
        token , place_id
    * response  
* 내가 한 북마크 가져오기
    * request  
        token
    * response  
        place 의 배열형태

> 논의 해야될 사항

**Comment by KIMJINOH97** [comment]
굳굳. 아마 request 보낼 때 /user/{user_id}/bookmark/{place_id} 이런식으로 하면 될듯 
나머지도 비슷하게 하면 될거 같습니다.
